let translateADS = {
    'en' :
    {
        addBTN: 'Add',
        labelFilterDate: 'Filter by Start Date and End Date',
        buttonSelectDate: 'Select Start Date & End Date',
        textFilterInputs: 'Filter by City || Ads Location || Ads Service',
        startDate: 'Start Date',
        endDate: 'End Date',
        labelCountry: 'Country',
        optionCountry: 'choose a country',
        labelCity: 'City',
        optionCity: 'choose a city',
        labelAdvertisementLocation: 'Location',
        optionAdvertisementLocation: 'choose a location',
        labelAdvertisementService: 'Service',
        optionAdvertisementService: 'choose a service',
        TableHeader: [
            "Image",
            "Service",
            "Start-Date",
            "End-Date",
            "Location",
            "Action",
        ],
        ActionsLabel: 'Actions',
        headerModalDel: 'Delete Advertisement',
        btnModalDel: 'Delete Now',
        labelImageInput: 'Ads Image',
        labelCountryInput: 'Country',
        labelCityInput: 'City',
        labelAdsServiceInput: 'Ads Service',
        labelAdsLocationInput: 'Ads Location',
        labelStartInput: 'Start Date',
        labelEndInput: 'End Date',
        labelLinkInput: 'ID Link',
        optionAdvertisementLink: 'choose a link',
        LabelAddPage: 'Add new Ads',
        SaveBTN: 'Save',
        CancelBTN: 'Cancel',
        LabelEditPage: 'Edit the Ads',
    },
    'ar' :
    {
        addBTN: 'إضافـة',
        labelFilterDate: 'البحث بواسطـة تاريـخ البـدء و تاريخ الإنتهاء',
        buttonSelectDate: 'تحديـد تاريـخ البـدء وتاريخ الإنتهـاء',
        textFilterInputs: 'البحث بواسطة المدينـة || موقـع الإعـلان || خدمـة الإعـلان',
        startDate: 'تاريـخ البدء',
        endDate: 'تاريـخ الإنتهاء',
        labelCountry: 'البلد',
        optionCountry: 'اختر البلد',
        labelCity: 'المدينـة',
        optionCity: 'اختر المدينـة',
        labelAdvertisementLocation: 'موقـع الإعـلان',
        optionAdvertisementLocation: 'اختـر الموقـع',
        labelAdvertisementService: 'خدمـة الإعـلان',
        optionAdvertisementService: 'اختـر الخدمـة',
        TableHeader: [
            "الصـورة",
            "الخدمـة",
            "تاريـخ البدء",
            "تاريـخ الإنتهـاء",
            "الموقـع",
            "الإجـراء",
        ],
        ActionsLabel: 'الإجـراءات',
        headerModalDel: 'حـذف الإعـلان',
        btnModalDel: 'حـذف الآن',
        labelImageInput: 'صـورة الإعـلان',
        labelCountryInput: 'البلـد',
        labelCityInput: 'المدينـة',
        labelAdsServiceInput: 'خدمـة الإعـلان',
        labelAdsLocationInput: 'موقـع الإعـلان',
        labelStartInput: 'تاريـخ البـدء',
        labelEndInput: 'تاريـخ الإنتهـاء',
        labelLinkInput: 'الرابــط',
        optionAdvertisementLink: 'اختـر الرابـط',
        LabelAddPage: 'إضافـة إعـلان جديـد',
        SaveBTN: 'حفـظ',
        CancelBTN: 'رجـوع',
        LabelEditPage: 'تعديــل الإعـلان',
    }
}


export default translateADS